module KnowledgeBase where

import Data.Text (Text)
import GHC.Generics (Generic)
import Data.Aeson (ToJSON, FromJSON)

data Movie = Movie
  { title :: Text
  , genres :: [Text]
  , director :: Text
  } deriving (Show, Eq, Generic)

instance ToJSON Movie
instance FromJSON Movie

movies :: [Movie]
movies =
  [ Movie "The Shawshank Redemption" ["drama", "crime"] "Frank Darabont"
  , Movie "The Godfather" ["crime", "drama"] "Francis Ford Coppola"
  , Movie "The Dark Knight" ["action", "crime", "drama"] "Christopher Nolan"
  , Movie "Schindler's List" ["biography", "drama", "history"] "Steven Spielberg"
  , Movie "12 Angry Men" ["drama", "crime"] "Sidney Lumet"
  , Movie "Pulp Fiction" ["crime", "drama"] "Quentin Tarantino"
  , Movie "The Lord of the Rings: The Return of the King" ["action", "adventure", "drama"] "Peter Jackson"
  , Movie "The Good, the Bad and the Ugly" ["western", "adventure"] "Sergio Leone"
  , Movie "Fight Club" ["drama", "thriller"] "David Fincher"
  , Movie "Forrest Gump" ["drama", "romance"] "Robert Zemeckis"
  , Movie "Inception" ["sci-fi", "action", "thriller"] "Christopher Nolan"
  , Movie "The Matrix" ["sci-fi", "action"] "Lana Wachowski"
  , Movie "Goodfellas" ["biography", "crime", "drama"] "Martin Scorsese"
  , Movie "Seven Samurai" ["action", "adventure", "drama"] "Akira Kurosawa"
  , Movie "City of God" ["crime", "drama"] "Fernando Meirelles"
  , Movie "The Silence of the Lambs" ["crime", "drama", "thriller"] "Jonathan Demme"
  , Movie "It's a Wonderful Life" ["drama", "family", "fantasy"] "Frank Capra"
  , Movie "Saving Private Ryan" ["drama", "war"] "Steven Spielberg"
  , Movie "Parasite" ["drama", "thriller"] "Bong Joon-ho"
  , Movie "Interstellar" ["sci-fi", "drama", "adventure"] "Christopher Nolan"
  , Movie "Spirited Away" ["animation", "family", "fantasy"] "Hayao Miyazaki"
  , Movie "The Green Mile" ["crime", "drama", "fantasy"] "Frank Darabont"
  , Movie "Life Is Beautiful" ["comedy", "drama", "romance"] "Roberto Benigni"
  , Movie "The Intouchables" ["biography", "comedy", "drama"] "Olivier Nakache"
  , Movie "Whiplash" ["drama", "music"] "Damien Chazelle"
  , Movie "Gladiator" ["action", "adventure", "drama"] "Ridley Scott"
  , Movie "The Prestige" ["drama", "mystery", "sci-fi"] "Christopher Nolan"
  , Movie "The Departed" ["crime", "drama", "thriller"] "Martin Scorsese"
  , Movie "The Pianist" ["biography", "drama", "music"] "Roman Polanski"
  , Movie "The Lion King" ["animation", "adventure", "drama"] "Roger Allers"
  , Movie "Back to the Future" ["adventure", "comedy", "sci-fi"] "Robert Zemeckis"
  , Movie "Terminator 2: Judgment Day" ["action", "sci-fi"] "James Cameron"
  , Movie "Alien" ["horror", "sci-fi"] "Ridley Scott"
  , Movie "American Beauty" ["drama", "romance"] "Sam Mendes"
  , Movie "The Great Dictator" ["comedy", "drama", "war"] "Charlie Chaplin"
  , Movie "Avengers: Endgame" ["action", "adventure", "sci-fi"] "Anthony Russo"
  , Movie "Django Unchained" ["drama", "western"] "Quentin Tarantino"
  , Movie "The Shining" ["drama", "horror"] "Stanley Kubrick"
  , Movie "Memento" ["mystery", "thriller"] "Christopher Nolan"
  , Movie "Apocalypse Now" ["drama", "war"] "Francis Ford Coppola"
  , Movie "WALL·E" ["animation", "adventure", "family"] "Andrew Stanton"
  , Movie "The Lives of Others" ["drama", "thriller"] "Florian Henckel von Donnersmarck"
  , Movie "Oldboy" ["action", "drama", "mystery"] "Park Chan-wook"
  , Movie "Princess Mononoke" ["animation", "adventure", "fantasy"] "Hayao Miyazaki"
  , Movie "Once Upon a Time in the West" ["western", "drama"] "Sergio Leone"
  , Movie "Coco" ["animation", "adventure", "family"] "Lee Unkrich"
  , Movie "Braveheart" ["biography", "drama", "history"] "Mel Gibson"
  , Movie "Toy Story" ["animation", "adventure", "comedy"] "John Lasseter"
  , Movie "Amadeus" ["biography", "drama", "music"] "Milos Forman"
  , Movie "3 Idiots" ["comedy", "drama"] "Rajkumar Hirani"
  , Movie "The Hunt" ["drama", "thriller"] "Thomas Vinterberg"
  , Movie "Requiem for a Dream" ["drama", "psychological"] "Darren Aronofsky"
  , Movie "The Truman Show" ["drama", "sci-fi"] "Peter Weir"
  , Movie "The Sixth Sense" ["mystery", "thriller", "drama"] "M. Night Shyamalan"
  , Movie "The Grand Budapest Hotel" ["comedy", "drama"] "Wes Anderson"
  , Movie "Her" ["drama", "romance", "sci-fi"] "Spike Jonze"
  , Movie "The Imitation Game" ["biography", "drama", "thriller"] "Morten Tyldum"
  , Movie "Spotlight" ["biography", "drama", "history"] "Tom McCarthy"
  , Movie "Blade Runner 2049" ["sci-fi", "drama"] "Denis Villeneuve"
  , Movie "Joker" ["crime", "drama", "thriller"] "Todd Phillips"
  , Movie "The Social Network" ["biography", "drama"] "David Fincher"
  , Movie "No Country for Old Men" ["crime", "drama", "thriller"] "Ethan Coen"
  , Movie "Prisoners" ["crime", "drama", "mystery"] "Denis Villeneuve"
  , Movie "Room" ["drama", "thriller"] "Lenny Abrahamson"
  , Movie "The Revenant" ["action", "adventure", "drama"] "Alejandro González Iñárritu"
  , Movie "Gone Girl" ["drama", "mystery", "thriller"] "David Fincher"
  , Movie "Black Swan" ["drama", "thriller"] "Darren Aronofsky"
  , Movie "Shutter Island" ["mystery", "thriller"] "Martin Scorsese"
  , Movie "The Theory of Everything" ["biography", "drama", "romance"] "James Marsh"
  , Movie "The Big Short" ["biography", "comedy", "drama"] "Adam McKay"
  , Movie "La La Land" ["comedy", "drama", "music"] "Damien Chazelle"
  , Movie "1917" ["drama", "war"] "Sam Mendes"
  , Movie "The Shape of Water" ["drama", "fantasy", "romance"] "Guillermo del Toro"
  , Movie "A Beautiful Mind" ["biography", "drama"] "Ron Howard"
  , Movie "Arrival" ["drama", "mystery", "sci-fi"] "Denis Villeneuve"
  , Movie "The Wolf of Wall Street" ["biography", "crime", "drama"] "Martin Scorsese"
  , Movie "Slumdog Millionaire" ["drama", "romance"] "Danny Boyle"
  , Movie "Inside Out" ["animation", "adventure", "comedy"] "Pete Docter"
  , Movie "Up" ["animation", "adventure", "comedy"] "Pete Docter"
  , Movie "Ratatouille" ["animation", "comedy", "family"] "Brad Bird"
  , Movie "Zootopia" ["animation", "adventure", "comedy"] "Byron Howard"
  , Movie "The Incredibles" ["animation", "action", "adventure"] "Brad Bird"
  , Movie "Monsters, Inc." ["animation", "adventure", "comedy"] "Pete Docter"
  , Movie "How to Train Your Dragon" ["animation", "action", "adventure"] "Dean DeBlois"
  , Movie "Tangled" ["animation", "adventure", "comedy"] "Nathan Greno"
  , Movie "Frozen" ["animation", "adventure", "comedy"] "Chris Buck"
  , Movie "Moana" ["animation", "adventure", "comedy"] "Ron Clements"
  ]